server:
  port: 8081

spring:
  datasource:
    password: mariadb
    username: root
    url: jdbc:mysql://localhost:5506/supplier
  jpa:
    hibernate:
      ddl-auto: create

  application:
    name: supplier

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
