spring:
  application:
    name: storefront

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

supplier:
  url: http://supplier